(() => {
  'use strict';
  const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  let scene;
  try {scene=new RaceScene($('world'));} catch(error){$('menu').innerHTML='<h2>Unable to start 3D graphics</h2><p>Enable hardware acceleration and reload in a modern browser.</p>';console.error(error);return;}
  let modelReady=!scene.player?.userData.ready;
  if(!modelReady){$('start').disabled=true;$('start').textContent='LOADING YOUR M5…';scene.player.userData.ready.then(()=>{modelReady=true;$('start').disabled=false;$('start').innerHTML='START YOUR ENGINE <span>↗</span>';}).catch(error=>{$('start').textContent='MODEL LOAD FAILED — RELOAD';console.error(error);});}
  const state={mode:'menu',distance:0,speed:0,speedLevel:0,speedMultiplier:1,x:0,steer:0,nitro:100,health:100,elapsed:0,score:0,combo:1,nearMisses:0,camera:0,traffic:[],boosting:false,braking:false};
  const keys=new Set(),touch={left:false,right:false,boost:false,brake:false};
  let last=0,countdown=3,spawnTimer=0,immunity=0,noticeTime=0,comboTime=0,previousMode='playing',best=0;
  try{best=Number(localStorage.getItem('nightshift-score'))||0;}catch{}
  $('menu-best').innerHTML=`${best.toLocaleString()} <small>PTS</small>`;
  class EngineAudio {
    constructor(){this.muted=false;this.ctx=null;}
    async start(){try{if(!this.ctx){const A=window.AudioContext||window.webkitAudioContext;this.ctx=new A();this.gain=this.ctx.createGain();this.gain.gain.value=0;this.gain.connect(this.ctx.destination);this.filter=this.ctx.createBiquadFilter();this.filter.type='lowpass';this.filter.frequency.value=700;this.filter.connect(this.gain);this.osc=[];for(const type of ['sawtooth','triangle']){const o=this.ctx.createOscillator();o.type=type;o.connect(this.filter);o.start();this.osc.push(o);}}await this.ctx.resume();}catch{this.muted=true;}}
    update(){if(!this.ctx)return;const active=state.mode==='playing'&&!this.muted,t=this.ctx.currentTime,gear=Math.min(7,1+Math.floor(state.speed/42)),rpm=state.speed%42;this.osc[0].frequency.setTargetAtTime(36+rpm*1.5+gear*4,t,.07);this.osc[1].frequency.setTargetAtTime(72+rpm*3+gear*8,t,.07);this.filter.frequency.setTargetAtTime(state.boosting?1100:400+state.speed*2,t,.1);this.gain.gain.setTargetAtTime(active?Math.min(.09,.026+state.speed*.000055):0,t,.08);}
    beep(frequency=700,duration=.12){if(!this.ctx||this.muted)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.frequency.value=frequency;o.connect(g);g.connect(this.ctx.destination);g.gain.setValueAtTime(.06,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.start(t);o.stop(t+duration);}
  }
  const audio=new EngineAudio();
  function clearInput(){keys.clear();for(const k in touch)touch[k]=false;}
  function notice(message,seconds=2){$('notice').textContent=message;noticeTime=seconds;}
  function start(){if(!modelReady)return;Object.assign(state,{mode:'countdown',distance:0,speed:0,speedLevel:0,speedMultiplier:1,x:0,steer:0,nitro:100,health:100,elapsed:0,score:0,combo:1,nearMisses:0,traffic:[],boosting:false,braking:false});clearInput();countdown=3;spawnTimer=1;immunity=0;comboTime=0;$('menu').hidden=true;$('overlay').hidden=true;$('hud').hidden=false;$('car-info').hidden=true;document.body.classList.add('playing');$('countdown').hidden=false;$('countdown').textContent='3';$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause game');notice('ENDLESS RUN / SPEED +10% EVERY 15 SECONDS',4);audio.start();audio.beep(500);updateHUD();}
  function pause(){if(state.mode==='paused'){state.mode=previousMode;$('overlay').hidden=true;$('pause').textContent='Ⅱ';$('pause').setAttribute('aria-label','Pause game');audio.start();return;}if(!['playing','countdown'].includes(state.mode))return;previousMode=state.mode;state.mode='paused';clearInput();state.boosting=false;$('overlay').hidden=false;$('dialog-label').textContent='RUN PAUSED';$('dialog-title').textContent='PIT STOP.';$('dialog-copy').textContent='Steer with A / D. Brake with S. Boost with Space. C changes camera. Your speed-increase timer is paused too.';$('resume').hidden=false;$('restart').textContent='RESTART RUN';$('pause').textContent='▶';$('pause').setAttribute('aria-label','Resume game');}
  function finish(reason='CAR TOTALLED'){state.mode='crashed';state.boosting=false;clearInput();$('countdown').hidden=true;const score=Math.floor(state.score+state.distance);if(score>best){best=score;try{localStorage.setItem('nightshift-score',String(best));}catch{}}$('overlay').hidden=false;$('dialog-label').textContent=reason;$('dialog-title').textContent='RUN ENDED.';$('dialog-copy').textContent=`${score.toLocaleString()} points · ${(state.distance/1000).toFixed(2)} km · ${state.nearMisses} close passes · Best ${best.toLocaleString()}`;$('resume').hidden=true;$('restart').textContent='DRIVE AGAIN ↗';audio.beep(120,.4);}
  function hit(amount){if(immunity>0)return;state.health=Math.max(0,state.health-amount);state.speed*=.48;state.combo=1;immunity=1.6;scene.impact();audio.beep(70,.24);notice(`COLLISION / −${amount}% CONDITION`);$('impact').classList.add('flash');setTimeout(()=>$('impact').classList.remove('flash'),250);if(state.health<=0)finish();}
  function update(dt){
    if(state.mode==='countdown'){const before=Math.ceil(countdown);countdown-=dt;if(Math.ceil(countdown)!==before)audio.beep(countdown>0?500:1000);$('countdown').textContent=Math.max(1,Math.ceil(countdown));if(countdown<=0){state.mode='playing';state.speed=35;$('countdown').hidden=true;notice('GO / FIND YOUR LINE',2);}return;}
    if(state.mode!=='playing')return;
    state.elapsed+=dt;immunity=Math.max(0,immunity-dt);
    const speedLevel=Math.floor((state.elapsed+1e-8)/15);
    if(speedLevel>state.speedLevel){const increase=Math.pow(1.1,speedLevel-state.speedLevel);state.speed*=increase;state.speedLevel=speedLevel;state.speedMultiplier=Math.pow(1.1,speedLevel);notice(`PACE INCREASED / +10% / ${Math.round(state.speedMultiplier*100)}% PACE`,2.5);}
    state.braking=keys.has('KeyS')||keys.has('ArrowDown')||touch.brake;state.boosting=(keys.has('Space')||touch.boost)&&state.nitro>1&&!state.braking;
    const gas=keys.has('KeyW')||keys.has('ArrowUp'),target=state.braking?40:(state.boosting?300:gas?240:215)*state.speedMultiplier,rate=state.braking?2.3:state.boosting?1.1:.38;state.speed+=(target-state.speed)*Math.min(1,dt*rate);state.nitro=clamp(state.nitro+(state.boosting?-24:9)*dt,0,100);
    const input=(keys.has('KeyD')||keys.has('ArrowRight')||touch.right?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')||touch.left?1:0);state.steer+=(input-state.steer)*Math.min(1,dt*7);
    const oldSlope=scene.roadSlope(state.distance),move=state.speed/3.6*dt;state.distance+=move;const newSlope=scene.roadSlope(state.distance);state.x+=state.steer*dt*(3.7+state.speed*.012)-(newSlope-oldSlope)*state.speed*.14;
    if(Math.abs(state.x)>5.92){state.x=clamp(state.x,-6.05,6.05);hit(18);}if(state.mode!=='playing')return;
    spawnTimer-=dt;if(spawnTimer<=0){const lane=Math.floor(Math.random()*4),x=(lane-1.5)*3.5,s=state.distance+170+Math.random()*40;if(!state.traffic.some(c=>Math.abs(c.s-s)<20&&Math.abs(c.x-x)<3))state.traffic.push({x,s,speed:85+Math.random()*45,passed:false,target:x,change:4+Math.random()*5});spawnTimer=Math.max(.8,1.6-state.distance/7000);}
    for(const c of state.traffic){const previousGap=c.s-(state.distance-move);c.s+=c.speed/3.6*dt;c.change-=dt;if(c.change<0&&c.s-state.distance>40){const next=clamp(c.target+(Math.random()>.5?3.5:-3.5),-5.25,5.25);if(!state.traffic.some(other=>other!==c&&Math.abs(other.s-c.s)<20&&Math.abs(other.x-next)<2.9))c.target=next;c.change=6;}c.x+=(c.target-c.x)*Math.min(1,dt*.65);const dz=c.s-state.distance,dx=Math.abs(c.x-state.x);if((Math.abs(dz)<4.55||(previousGap>4.55&&dz< -4.55))&&dx<1.85){hit(40);c.passed=true;}if(dz<-5&&!c.passed){c.passed=true;if(dx<2.9&&immunity===0){state.nearMisses++;state.score+=250*state.combo;state.combo=Math.min(5,state.combo+1);comboTime=5;state.nitro=Math.min(100,state.nitro+12);notice(`CLOSE PASS / ${state.combo}× COMBO / +12 NITRO`);audio.beep(800,.06);}else state.score+=60;}}
    state.traffic=state.traffic.filter(c=>c.s>state.distance-30);comboTime-=dt;if(comboTime<=0)state.combo=1;
    noticeTime-=dt;if(noticeTime<=0)$('notice').textContent=state.boosting?'NITRO ENGAGED':'';
  }
  function updateHUD(){$('distance').textContent=(state.distance/1000).toFixed(2);$('best').textContent=`NEXT +10% IN ${Math.max(0,15*(state.speedLevel+1)-state.elapsed).toFixed(1)} S`;$('speed').textContent=Math.round(state.speed);$('speed-fill').style.width=`${clamp(state.speed/(300*state.speedMultiplier)*100,0,100)}%`;$('boost-fill').style.width=`${state.nitro}%`;$('nitro-label').textContent=state.boosting?'ACTIVE':`${Math.round(state.nitro)}%`;$('timer').textContent=`${Math.floor(state.elapsed/60)}:${String(Math.floor(state.elapsed%60)).padStart(2,'0')}`;$('score').textContent=Math.floor(state.score+state.distance).toLocaleString();$('health-fill').style.width=`${state.health}%`;$('health-label').textContent=`${state.health}%`;$('gear').textContent=`${Math.min(7,1+Math.floor(state.speed/42))}`;$('pace').textContent=`${state.speedMultiplier.toFixed(2)}×`;}
  $('start').onclick=start;$('restart').onclick=start;$('pause').onclick=pause;$('resume').onclick=pause;
  $('mute').onclick=()=>{audio.muted=!audio.muted;$('mute').textContent=audio.muted?'SOUND OFF':'SOUND ON';$('mute').setAttribute('aria-pressed',String(audio.muted));};
  const changeCamera=()=>{state.camera=(state.camera+1)%2;$('camera').textContent=state.camera?'HOOD CAM':'CHASE CAM';};$('camera').onclick=changeCamera;
  addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.repeat){keys.add(e.code);return;}if(e.code==='KeyP'||e.code==='Escape'){pause();return;}if(e.code==='KeyC'){changeCamera();return;}if(e.code==='KeyM'){$('mute').click();return;}if(e.code==='Enter'&&['menu','crashed'].includes(state.mode)){start();return;}keys.add(e.code);});addEventListener('keyup',e=>keys.delete(e.code));
  addEventListener('blur',()=>{clearInput();if(['playing','countdown'].includes(state.mode))pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['playing','countdown'].includes(state.mode))pause();});
  for(const id of ['left','right','boost','brake']){const el=$(id);el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);touch[id]=true;};el.onpointerup=el.onpointercancel=el.onlostpointercapture=()=>{touch[id]=false;};}
  window.nightshift={getState:()=>({...state,traffic:state.traffic.map(c=>({...c})),drawCalls:scene.renderer.info.render.calls,triangles:scene.renderer.info.render.triangles})};
  function frame(t){const dt=Math.min((t-last)/1000||0,.05);last=t;update(dt);if(state.mode!=='menu')updateHUD();audio.update();scene.render(state,['paused','crashed'].includes(state.mode)?0:dt,t/1000);requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
