const {readFileSync}=require('node:fs');
const {join}=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const elements=new Map(),storage=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){}});return elements.get(id);};
class MockScene{constructor(){this.renderer={info:{render:{}}};}roadSlope(s){return Math.cos(s*.0028)*.0588+Math.cos(s*.006+.4)*.036;}impact(){}render(){}}
const context={console,RaceScene:MockScene,document:{getElementById:element,body:{classList:{add(){}}},addEventListener(){}},window:{},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},addEventListener(){},requestAnimationFrame(){},setTimeout(){}};
const source=readFileSync(join(__dirname,'../game.js'),'utf8').replace('function frame(t){','globalThis.test={state,start,update,pause,hit,finish,keys};function frame(t){');
vm.runInNewContext(source,context);const t=context.test;
const step=seconds=>{for(let i=0;i<Math.ceil(seconds*60);i++)t.update(1/60);};
t.start();assert.equal(t.state.mode,'countdown');step(3.1);assert.equal(t.state.mode,'playing');
step(1);assert(t.state.distance>0);t.keys.add('KeyD');step(.2);t.keys.clear();assert(t.state.x>.1);
t.keys.add('Space');step(.4);assert(t.state.boosting);assert(t.state.nitro<100);t.keys.clear();
t.pause();const distance=t.state.distance;step(1);assert.equal(t.state.distance,distance);t.pause();assert.equal(t.state.mode,'playing');
t.state.traffic=[];t.state.x=0;t.state.distance=3999.9;t.state.speed=200;t.update(.02);assert.equal(t.state.mode,'playing');assert(t.state.distance>4000,'No finish line at 4 km');
t.hit(40);assert.equal(t.state.health,60);t.hit(40);assert.equal(t.state.health,60,'Collision immunity prevents per-frame damage');
t.state.traffic=[];t.state.x=0;step(1.7);t.hit(40);assert.equal(t.state.health,20);
t.state.traffic=[];t.state.x=0;step(1.7);t.hit(40);assert.equal(t.state.mode,'crashed');
assert(storage.has('nightshift-score'));
t.start();step(2);assert.equal(t.state.elapsed,0,'Pre-race countdown does not advance speed timer');step(1.1);
t.state.elapsed=14.9;t.state.speed=215;t.state.x=0;t.state.traffic=[];
t.update(.05);assert.equal(t.state.speedLevel,0);assert.equal(t.state.speedMultiplier,1);
t.update(.05);assert.equal(t.state.speedLevel,1);assert(Math.abs(t.state.speed-236.5)<1e-8,'At 15 s cruise speed increases exactly 10%');
t.update(.01);assert.equal(t.state.speedLevel,1,'Do not increase twice in the same interval');
t.pause();const elapsed=t.state.elapsed,speed=t.state.speed;step(30);assert.equal(t.state.elapsed,elapsed);assert.equal(t.state.speed,speed);t.pause();
t.state.elapsed=29.95;t.state.speed=236.5;t.state.x=0;t.state.traffic=[];t.update(.05);assert.equal(t.state.speedLevel,2);assert(Math.abs(t.state.speedMultiplier-1.21)<1e-8);assert(Math.abs(t.state.speed-260.15)<1e-8,'Second increase compounds');
t.keys.add('KeyS');const beforeBrake=t.state.speed;t.update(.05);assert(t.state.speed<beforeBrake,'Braking still works after speed increases');t.keys.clear();
t.state.elapsed=89.95;t.state.distance=12000;t.state.x=0;t.state.traffic=[];t.update(.05);assert.equal(t.state.mode,'playing','No time or distance limit');assert(t.state.distance>12000);assert.equal(t.state.speedLevel,6);assert(Math.abs(t.state.speedMultiplier-1.1**6)<1e-8,'Catch up any crossed intervals');
t.start();assert.equal(t.state.health,100);assert.equal(t.state.distance,0);assert.equal(t.state.elapsed,0);assert.equal(t.state.speedLevel,0);assert.equal(t.state.speedMultiplier,1);
t.state.mode='playing';t.state.speed=1800;t.state.traffic=[{x:0,s:10,speed:85,passed:false,target:0,change:5}];t.update(.05);assert.equal(t.state.health,60,'Fast vehicles cannot tunnel through traffic between frames');
console.log('PASS: countdown, movement, steering, boost, pause, endless distance/time, collision damage/immunity, persistence, 15/30-second compounding, interval catch-up, braking and restart reset.');
